### ISSUE TITLE
What do you think about merging COM repository into SharpGenTools? 

### ISSUE THREAD

**Issue by nerzhulart** [SharpGenTools/SharpGenTools#142]
I can make this preserving git history.
It will make developing a lot easier

**Comment by jkoritzinsky** [comment]
I actually split them into separate repositories a while back since I felt that the COM support was nearly feature-complete at the time. Additionally, getting the project-to-project reference between SharpGen.Runtime and SharpGen.Runtime.COM working with binding flow would require some custom MSBuild hackery.

I’d personally like to keep them separate if possible.

**Comment by nerzhulart** [comment]
Got it
