### ISSUE TITLE
Marshal return string parameter

### ISSUE THREAD

**Issue by amerkoleci** [SharpGenTools/SharpGenTools#177]
Not sure if this is bug, or way to hide the mapping, how would be possible to marshal return string type:
The function I try to map is:
```
const wchar_t* IDxcBlobUtf16::GetStringPointer()
```

Now I get an unasigned string:
```
internal unsafe System.String GetStringPointer()
{
  System.String __result__;
  System.IntPtr __result__native;
  __result__native = Vortice.Dxc.LocalInterop.CalliStdCallSystemIntPtr(this._nativePointer, (*(void ***)this._nativePointer)[6]);
   return __result__;
 }
```
@andrew-boyarshin 

Thanks

**Comment by andrew-boyarshin** [comment]
I will take a look this weekend. Fixed statement wasn't generated, [StringMarshaller](https://github.com/andrew-boyarshin/SharpGenTools/blob/mine/SharpGen/Generator/Marshallers/StringMarshaller.cs) should be the one to blame.

**Comment by andrew-boyarshin** [comment]
@jkoritzinsky could you briefly explain to me what purpose does `singleStackFrame` serve? I'm having trouble understanding its necessity. It was introduced in #52, and I can't figure out why. It was mostly `MarshalPinnableElements` := `!singleStackFrame` back then, which I'm guessing was performance optimization (pinning instead of marshalling, when possible). How possible do you think dropping `singleStackFrame` is?

**Comment by andrew-boyarshin** [comment]
Okay, judging by `GenerateNativeCleanup` callers, `singleStackFrame` is `false` for struct (public <-> `__Native`) marshalling, `true` for the rest (parameters, return values).
