### ISSUE TITLE
Github CI and artifacts

### ISSUE THREAD

**Issue by amerkoleci** [SharpGenTools/SharpGenTools#182]
Would be cool to move to github workflow and generate packages using host them on github, only stable packages like 2.0 will go on nuget.

This way I can test nightly builds. 

I can submit PR

**Comment by jkoritzinsky** [comment]
I don't have the time to hook this up, but I'd be 100% down for moving to Github Actions.

**Comment by andrew-boyarshin** [comment]
I don't have a strong opinion on this matter, but I don't think it's necessary to migrate from AzDO to GH Actions. AzDO is actually better at the moment (more features, better hosted agent machine pool). AzDO/GH CI devs also recommended .NET infra team to wait until 2022 before considering the migration. What _is_ necessary, however, is to migrate off MyGet. The most inconvenient NuGet service I've ever tried. Both AzDO and GH provide custom NuGet feeds, makes sense to use them.

**Comment by amerkoleci** [comment]
For SharpGen github workflow is ok, we don't need nothing more that Azure pipelines gives.

**Comment by jkoritzinsky** [comment]
As someone who also works on dotnet/runtime, just because they need to wait to move doesn't mean we need to wait. Our build system is significantly simpler. I think Github actions + Github packages for night lies would be better for overall maintainability since it will all be linked to the Github org.
