### ISSUE TITLE
Fix TODOs

### ISSUE THREAD

**Issue by jkoritzinsky** [SharpGenTools/SharpGenTools#7]
There are a number of TODO's in the code that may or may not be outdated or invalid. Can we go through and clean them up/fix them?

**Comment by xoofx** [comment]
A few comments that I recall on the work I wanted to do to extract SharpGen but never did it:

- Codegen is using T4 templating, and it is very slow (parsing templates, compiling assemblies...etc.), quite laborious to update, code is intermixed...etc. I remember that I evaluated two options, 1) Roslyn, and 2) CodeDomProvider. I end-up with CodeDomProivder, as It was a lot more easier to interact with the code, and easier also to pass some constructions not supported by codedom as well (with some custom writers). A custom codedom provider could also be done entirely in C#.
- The handling of marshaling is really not standardized between structs and function arguments. The code in CppParameter (with the associated code in Method.tt), is messy and ugly, developed to get things done, but not really designed to handle any kind of marshaling scenarios. 
- There was also an idea of making SharpDX a lot more lighter by using almost only structs instead of managed objects for COM references (see for example issue #722). I doesn't have to be done straight on the SharpGen refactoring. But this is something to keep in mind.
- There was also an idea to embed directly CLang via DllImport (using [ClangSharp](https://github.com/Microsoft/ClangSharp)) instead of using CastXML. It would require quite a lot more work though...

Overall, SharpGen is a very old piece of code, with several hacks, not well written and organized, It did just the bare job.

**Comment by dzmitry-lahoda** [comment]
C# got `unmanaged` constraint. And hopefully will do `generic unamanged` https://github.com/dotnet/csharplang/issues/1504. 

Are these improvements allow for better `making SharpDX a lot more lighter by using almost only structs instead of managed objects for COM references` or are irrelevant?

**Comment by xoofx** [comment]
> Are these improvements allow for better making SharpDX a lot more lighter by using almost only structs instead of managed objects for COM references or are irrelevant?

It doesn't help much in this case, as the struct is used only as a this pointer and would have only a single `IntPtr` for the COM pointer. The difference is in the way to handle interface inheritance and how to expose COM methods (via extension method via the interface as described [here](https://github.com/sharpdx/SharpDX/issues/722#issuecomment-195946950) or directly via instance methods on the struct - duplicating them between inheritance). The Unmanaged constraint is only useful for generic parameter contraints, but there was barely any in the SharpDX code base.

**Comment by dzmitry-lahoda** [comment]
Hm, need to think about. May be ould use `T` as `type` tag and so could write extensions method against `T*` or `Com2<T>`,  nor around wrapper of storage of `IntPtr` or `void*`.

```
    public unsafe struct Com2<T> where T : unmanaged
    {
        T* ptr;
    }
```

**Comment by xoofx** [comment]
It doesn't bring any value, as we can't replicate smart pointers in C# where the `->` could be delegated to the internal `T* ptr`. At best, you can have `Com<T>` but using an internal IntPtr should be enough and T would not be required to have the unmanaged constraint, because it would be just an empty interface, while all the methods would be exposed via extension methods. In the end, it should be similar to the approach described above. But it would require still a significant work in SharpDX, as there are many COM callbacks that would require some special handling (and today, we are requiring to inherit from a class anyway...)

**Comment by jkoritzinsky** [comment]
I'm closing this for now. May re-investigate in the future.
